name: pkg.pr.new

permissions: {}

on:
  push: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - run: pnpm install
      - run: pnpm build
      - name: Publish to pkg.pr.new
        run: pnpx pkg-pr-new publish --no-template --pnpm './packages/*'
